version: '3.8'

services:
  web:
    build: .
    command: 
      - /bin/sh
      - -c
      - |
        python init.py
        flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.flaskenv
    depends_on:
      - postgres

  postgres:
      #image: docker.superz.ir/utils/postgis:latest
      image: mdillon/postgis:latest
      container_name: postgres
      ports:
        - 5432:5432
      environment:
          POSTGRES_PORT: 5432
          POSTGRES_DB: "peterpark"
          POSTGRES_USER: "peterpark"
          POSTGRES_PASSWORD: "pass"
      volumes:
          - postgres-data:/var/lib/postgresql/data/


volumes:
    postgres-data:

